[package]
name = "tha"
version = "0.1.0"
authors = ["Christophe Pollet"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
peek-nth = "0.2.0"

[[bin]]
name = "tha"
path = "src/asm/main.rs"